require "colorize"
require "sxp"
require "optparse"

require_relative "./synchrony/version"
require_relative "./synchrony/info_display"
require_relative "./synchrony/lexer"
require_relative "./synchrony/ast"
require_relative "./synchrony/parser"
require_relative "./synchrony/compiler"
require_relative "./synchrony/runner"
require_relative "./synchrony/code"
require_relative "./synchrony/visitor"
require_relative "./synchrony/pretty_printer"
require_relative "./synchrony/name_resolver"
require_relative "./synchrony/type_checker"
require_relative "./synchrony/symtable"
